//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoxaStudy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<int> IdClothes { get; set; }
        public Nullable<int> IdTypeMaterial { get; set; }
    
        public virtual Clothe Clothe { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
    }
}
